// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {version} from '../models';

export function GetConfigJSON():Promise<string>;

export function GetConfigPath():Promise<string>;

export function GetVersionInfo():Promise<version.Info>;

export function Greet(arg1:string):Promise<string>;

export function ResetConfig():Promise<void>;

export function UpdateConfig(arg1:string):Promise<void>;
