// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfigJSON() {
  return window['go']['backend']['App']['GetConfigJSON']();
}

export function GetConfigPath() {
  return window['go']['backend']['App']['GetConfigPath']();
}

export function Greet(arg1) {
  return window['go']['backend']['App']['Greet'](arg1);
}

export function ResetConfig() {
  return window['go']['backend']['App']['ResetConfig']();
}

export function UpdateConfig(arg1) {
  return window['go']['backend']['App']['UpdateConfig'](arg1);
}
