// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetWindowSize() {
  return window['go']['services']['PreferencesService']['GetWindowSize']();
}

export function SaveWindowMaximised(arg1) {
  return window['go']['services']['PreferencesService']['SaveWindowMaximised'](arg1);
}

export function SaveWindowSize(arg1, arg2) {
  return window['go']['services']['PreferencesService']['SaveWindowSize'](arg1, arg2);
}
