// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetWindowSize():Promise<number>;

export function SaveWindowMaximised(arg1:boolean):Promise<void>;

export function SaveWindowSize(arg1:number,arg2:number):Promise<void>;
