// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function HasOAuthToken() {
  return window['go']['services']['TokenService']['HasOAuthToken']();
}
